FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /app


COPY pom.xml .
RUN mvn dependency:go-offline


COPY src src

RUN mvn clean install -DskipTests

FROM openjdk:17-slim
WORKDIR /app

COPY --from=build /app/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
