spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      default-filters:
        - SetCookie
        - CustomTokenVerification
      routes:
        - id: auth-server
          predicates:
            - Path=/api/user/**
          uri: ${external.auth-service.url}

        - id: orchestrator-service
          predicates:
            - Path=/api/product/**,/api/device/**,/api/email/**,/api/history/**,/api/image/**,/api/news/**,/api/notification/**,/api/places/**

          uri: ${external.service-orchestration.url}

      discovery:
        locator:
          enabled: false

server:
  port: 8000
