server:
  port: 8081
  servlet:
    context-path: /api/user
spring:
  application:
    name: user-service
  jackson:
    defaultPropertyInclusion: "non_null"
  datasource:
    driverClassName: 'org.postgresql.Driver'
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    showSql: 'true'
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'

jwt:
  secret: myverysecuasdadsadasdaasdfawrfQuihfqwhf8q8fdq8whd9pQHPDFHqwudjQNDJqnuiHEUqwuiedjqwnweujhqweuhsdaeqaweaeawearekey

external:
  google: https://oauth2.googleapis.com/tokeninfo

kafka:
  url: ${KAFKA_URL}
