spring:
  jackson:
    defaultPropertyInclusion: "non_null"
  datasource:
    driverClassName: 'org.postgresql.Driver'
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    showSql: 'true'
    hibernate:
      ddl-auto: 'update'
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
  application:
    name: 'main-service'
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: openid,profile,email
      resource-server:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
security:
  supportedRegistrationSources:
    - GOOGLE
    - JWT

kafka:
  url: ${KAFKA_URL}

server:
  url: ${SERVER_URL}

jwt:
  secret-key: ${JWT_SECRET_KEY}
